// AUTO-GENERATED by scripts/download_banners.py — do not edit by hand.
// Re-run the script to refresh.

export interface Banner {
	path: string;
	name: string;
	source: string;
	copyright: string;
	game: 'elden_ring' | 'shadow_of_the_erdtree';
	type: string;
}

export const BANNERS: Banner[] = [
	{
		path: "/art/banners/elden-ring-screenshot-01.jpg",
		name: "ELDEN RING Screenshot 01",
		source: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_943bf6fe62352757d9070c1d33e50b92fe8539f1.1920x1080.jpg?t=1767883716",
		copyright: "ELDEN RING\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92022 FromSoftware, Inc.",
		game: "elden_ring",
		type: "screenshot"
	},
	{
		path: "/art/banners/elden-ring-screenshot-02.jpg",
		name: "ELDEN RING Screenshot 02",
		source: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_dcdac9e4b26ac0ee5248bfd2967d764fd00cdb42.1920x1080.jpg?t=1767883716",
		copyright: "ELDEN RING\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92022 FromSoftware, Inc.",
		game: "elden_ring",
		type: "screenshot"
	},
	{
		path: "/art/banners/elden-ring-screenshot-03.jpg",
		name: "ELDEN RING Screenshot 03",
		source: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_3c41384a24d86dddd58a8f61db77f9dc0bfda8b5.1920x1080.jpg?t=1767883716",
		copyright: "ELDEN RING\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92022 FromSoftware, Inc.",
		game: "elden_ring",
		type: "screenshot"
	},
	{
		path: "/art/banners/elden-ring-screenshot-04.jpg",
		name: "ELDEN RING Screenshot 04",
		source: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_e0316c76f8197405c1312d072b84331dd735d60b.1920x1080.jpg?t=1767883716",
		copyright: "ELDEN RING\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92022 FromSoftware, Inc.",
		game: "elden_ring",
		type: "screenshot"
	},
	{
		path: "/art/banners/elden-ring-screenshot-05.jpg",
		name: "ELDEN RING Screenshot 05",
		source: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_ef61b771ee6b269b1f0cb484233e07a0bfb5f81b.1920x1080.jpg?t=1767883716",
		copyright: "ELDEN RING\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92022 FromSoftware, Inc.",
		game: "elden_ring",
		type: "screenshot"
	},
	{
		path: "/art/banners/elden-ring-screenshot-06.jpg",
		name: "ELDEN RING Screenshot 06",
		source: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_b1b91299d7e4b94201ac840aa64de54d9f5cb7f3.1920x1080.jpg?t=1767883716",
		copyright: "ELDEN RING\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92022 FromSoftware, Inc.",
		game: "elden_ring",
		type: "screenshot"
	},
	{
		path: "/art/banners/elden-ring-screenshot-07.jpg",
		name: "ELDEN RING Screenshot 07",
		source: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_510a02cf3045e841e180f2b77fb87545e0c8b59d.1920x1080.jpg?t=1767883716",
		copyright: "ELDEN RING\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92022 FromSoftware, Inc.",
		game: "elden_ring",
		type: "screenshot"
	},
	{
		path: "/art/banners/elden-ring-screenshot-08.jpg",
		name: "ELDEN RING Screenshot 08",
		source: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_c494372930ca791bdc6221eca134f2270fb2cb9f.1920x1080.jpg?t=1767883716",
		copyright: "ELDEN RING\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92022 FromSoftware, Inc.",
		game: "elden_ring",
		type: "screenshot"
	},
	{
		path: "/art/banners/elden-ring-screenshot-09.jpg",
		name: "ELDEN RING Screenshot 09",
		source: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_fa6b881ef7c30522012ab2b2b83001e79baee093.1920x1080.jpg?t=1767883716",
		copyright: "ELDEN RING\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92022 FromSoftware, Inc.",
		game: "elden_ring",
		type: "screenshot"
	},
	{
		path: "/art/banners/elden-ring-screenshot-10.jpg",
		name: "ELDEN RING Screenshot 10",
		source: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/ss_c2baf8aada6140beee79d701d14043899e91af47.1920x1080.jpg?t=1767883716",
		copyright: "ELDEN RING\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92022 FromSoftware, Inc.",
		game: "elden_ring",
		type: "screenshot"
	},
	{
		path: "/art/banners/elden-ring-library-hero.jpg",
		name: "ELDEN RING Library Hero",
		source: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/library_hero.jpg?t=1767883716",
		copyright: "ELDEN RING\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92022 FromSoftware, Inc.",
		game: "elden_ring",
		type: "hero"
	},
	{
		path: "/art/banners/elden-ring-background-raw.jpg",
		name: "ELDEN RING Background Raw",
		source: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/page_bg_raw.jpg?t=1767883716",
		copyright: "ELDEN RING\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92022 FromSoftware, Inc.",
		game: "elden_ring",
		type: "background"
	},
	{
		path: "/art/banners/shadow-of-the-erdtree-screenshot-01.jpg",
		name: "Shadow of the Erdtree Screenshot 01",
		source: "https://static.bandainamcoent.eu/high/elden-ring/elden-ring/08-shadow-of-the-erdtree/elden-ring-expansion-SOTE/01-screenshot/ERSOTE-screenshot-1.png",
		copyright: "ELDEN RING Shadow of the Erdtree\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92024 FromSoftware, Inc.",
		game: "shadow_of_the_erdtree",
		type: "screenshot"
	},
	{
		path: "/art/banners/shadow-of-the-erdtree-screenshot-02.jpg",
		name: "Shadow of the Erdtree Screenshot 02",
		source: "https://static.bandainamcoent.eu/high/elden-ring/elden-ring/08-shadow-of-the-erdtree/elden-ring-expansion-SOTE/01-screenshot/ERSOTE-screenshot-2.png",
		copyright: "ELDEN RING Shadow of the Erdtree\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92024 FromSoftware, Inc.",
		game: "shadow_of_the_erdtree",
		type: "screenshot"
	},
	{
		path: "/art/banners/shadow-of-the-erdtree-screenshot-03.jpg",
		name: "Shadow of the Erdtree Screenshot 03",
		source: "https://static.bandainamcoent.eu/high/elden-ring/elden-ring/08-shadow-of-the-erdtree/elden-ring-expansion-SOTE/01-screenshot/ERSOTE-screenshot-3.png",
		copyright: "ELDEN RING Shadow of the Erdtree\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92024 FromSoftware, Inc.",
		game: "shadow_of_the_erdtree",
		type: "screenshot"
	},
	{
		path: "/art/banners/shadow-of-the-erdtree-screenshot-04.jpg",
		name: "Shadow of the Erdtree Screenshot 04",
		source: "https://static.bandainamcoent.eu/high/elden-ring/elden-ring/08-shadow-of-the-erdtree/elden-ring-expansion-SOTE/01-screenshot/ERSOTE-screenshot-4.png",
		copyright: "ELDEN RING Shadow of the Erdtree\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92024 FromSoftware, Inc.",
		game: "shadow_of_the_erdtree",
		type: "screenshot"
	},
	{
		path: "/art/banners/shadow-of-the-erdtree-screenshot-05.jpg",
		name: "Shadow of the Erdtree Screenshot 05",
		source: "https://static.bandainamcoent.eu/high/elden-ring/elden-ring/08-shadow-of-the-erdtree/elden-ring-expansion-SOTE/01-screenshot/ERSOTE-screenshot-5.png",
		copyright: "ELDEN RING Shadow of the Erdtree\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92024 FromSoftware, Inc.",
		game: "shadow_of_the_erdtree",
		type: "screenshot"
	},
	{
		path: "/art/banners/shadow-of-the-erdtree-screenshot-06.jpg",
		name: "Shadow of the Erdtree Screenshot 06",
		source: "https://static.bandainamcoent.eu/high/elden-ring/elden-ring/08-shadow-of-the-erdtree/elden-ring-expansion-SOTE/01-screenshot/ERSOTE-screenshot-6.png",
		copyright: "ELDEN RING Shadow of the Erdtree\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92024 FromSoftware, Inc.",
		game: "shadow_of_the_erdtree",
		type: "screenshot"
	},
	{
		path: "/art/banners/shadow-of-the-erdtree-screenshot-07.jpg",
		name: "Shadow of the Erdtree Screenshot 07",
		source: "https://static.bandainamcoent.eu/high/elden-ring/elden-ring/08-shadow-of-the-erdtree/elden-ring-expansion-SOTE/01-screenshot/ERSOTE-screenshot-7.png",
		copyright: "ELDEN RING Shadow of the Erdtree\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92024 FromSoftware, Inc.",
		game: "shadow_of_the_erdtree",
		type: "screenshot"
	},
	{
		path: "/art/banners/shadow-of-the-erdtree-screenshot-08.jpg",
		name: "Shadow of the Erdtree Screenshot 08",
		source: "https://static.bandainamcoent.eu/high/elden-ring/elden-ring/08-shadow-of-the-erdtree/elden-ring-expansion-SOTE/01-screenshot/ERSOTE-screenshot-8.png",
		copyright: "ELDEN RING Shadow of the Erdtree\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92024 FromSoftware, Inc.",
		game: "shadow_of_the_erdtree",
		type: "screenshot"
	},
	{
		path: "/art/banners/shadow-of-the-erdtree-screenshot-09.jpg",
		name: "Shadow of the Erdtree Screenshot 09",
		source: "https://static.bandainamcoent.eu/high/elden-ring/elden-ring/08-shadow-of-the-erdtree/elden-ring-expansion-SOTE/01-screenshot/ERSOTE-screenshot-9.png",
		copyright: "ELDEN RING Shadow of the Erdtree\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92024 FromSoftware, Inc.",
		game: "shadow_of_the_erdtree",
		type: "screenshot"
	},
	{
		path: "/art/banners/shadow-of-the-erdtree-screenshot-10.jpg",
		name: "Shadow of the Erdtree Screenshot 10",
		source: "https://static.bandainamcoent.eu/high/elden-ring/elden-ring/08-shadow-of-the-erdtree/elden-ring-expansion-SOTE/01-screenshot/ERSOTE-screenshot-10.png",
		copyright: "ELDEN RING Shadow of the Erdtree\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92024 FromSoftware, Inc.",
		game: "shadow_of_the_erdtree",
		type: "screenshot"
	},
	{
		path: "/art/banners/shadow-of-the-erdtree-screenshot-11.jpg",
		name: "Shadow of the Erdtree Screenshot 11",
		source: "https://static.bandainamcoent.eu/high/elden-ring/elden-ring/08-shadow-of-the-erdtree/elden-ring-expansion-SOTE/01-screenshot/ERSOTE-screenshot-11.png",
		copyright: "ELDEN RING Shadow of the Erdtree\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92024 FromSoftware, Inc.",
		game: "shadow_of_the_erdtree",
		type: "screenshot"
	},
	{
		path: "/art/banners/shadow-of-the-erdtree-wallpaper-png.jpg",
		name: "Shadow of the Erdtree Wallpaper PNG",
		source: "https://media-center.bandainamcoent.eu/games/elden-ring/elden-ring-shadow-of-the-erdtree-wallpaper-download.png",
		copyright: "ELDEN RING Shadow of the Erdtree\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92024 FromSoftware, Inc.",
		game: "shadow_of_the_erdtree",
		type: "wallpaper"
	},
	{
		path: "/art/banners/shadow-of-the-erdtree-key-art.jpg",
		name: "Shadow of the Erdtree Key Art",
		source: "https://us-east-1-bandai.graphassets.com/AXzioIclSWilEjFtsMJPwz/oBmYzq2Sk6LaaTvDhLAw",
		copyright: "ELDEN RING Shadow of the Erdtree\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92024 FromSoftware, Inc.",
		game: "shadow_of_the_erdtree",
		type: "key_art"
	},
	{
		path: "/art/banners/shadow-of-the-erdtree-key-art-red-variant.jpg",
		name: "Shadow of the Erdtree Key Art Red Variant",
		source: "https://us-east-1-bandai.graphassets.com/AXzioIclSWilEjFtsMJPwz/rmrBqkkeTHy2Aq6hcwom",
		copyright: "ELDEN RING Shadow of the Erdtree\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92024 FromSoftware, Inc.",
		game: "shadow_of_the_erdtree",
		type: "key_art"
	},
	{
		path: "/art/banners/shadow-of-the-erdtree-collector-edition-messmer-promo.jpg",
		name: "Shadow of the Erdtree Collector Edition Messmer Promo",
		source: "https://us-east-1-bandai.graphassets.com/AXzioIclSWilEjFtsMJPwz/hlpdWmnJQ9eIJBSTCoCy",
		copyright: "ELDEN RING Shadow of the Erdtree\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92024 FromSoftware, Inc.",
		game: "shadow_of_the_erdtree",
		type: "promo_art"
	},
	{
		path: "/art/banners/shadow-of-the-erdtree-background-raw.jpg",
		name: "Shadow of the Erdtree Background Raw",
		source: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2778580/page_bg_raw.jpg",
		copyright: "ELDEN RING Shadow of the Erdtree\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92024 FromSoftware, Inc.",
		game: "shadow_of_the_erdtree",
		type: "background"
	},
	{
		path: "/art/banners/shadow-of-the-erdtree-steam-screenshot.jpg",
		name: "Shadow of the Erdtree Steam Screenshot",
		source: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2778580/ss_c97bcad291f4f45d4be4594f34bd78921d961099.jpg",
		copyright: "ELDEN RING Shadow of the Erdtree\u2122 & \u00a9BANDAI NAMCO Entertainment Inc. / \u00a92024 FromSoftware, Inc.",
		game: "shadow_of_the_erdtree",
		type: "screenshot"
	},
];

/** Stable hash → pick a banner deterministically from a string (e.g. pseudo). */
export function pickBanner(key: string): Banner {
	if (BANNERS.length === 0) throw new Error('No banners available');
	let h = 2166136261;
	for (let i = 0; i < key.length; i++) {
		h ^= key.charCodeAt(i);
		h = Math.imul(h, 16777619);
	}
	return BANNERS[Math.abs(h) % BANNERS.length];
}
